#!/usr/bin/env bash
cd n
sleep 5m
screen -S bs -p 0 -X stuff "tellraw Ingin027 {"text":"[!] Starting Backup","bold":true,"underlined":true,"color":"red"}"
git add --all -- ':!bs' ':bedrock_server_symbols.debug'
git commit -m "Update"
/usr/bin/expect <<EOD
spawn git push
expect "Username for 'https://github.com':"
send "akulupaaa511\r"
expect "Password for 'https://akulupaaa511@github.com':"
send "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\r"
screen -S bs -p 0 -X stuff "tellraw Ingin027 {"text":"[!] Backup Finished","bold":true,"underlined":true,"color":"red"}"
./sb
